[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "no-store"

[[headers]]
  for = "/*.pdf"
  [headers.values]
    Cache-Control = "private, no-store"


